#Assignment 1
##Q1: Questions on Basic NumPy Array
(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])


In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)

arr_rev= arr[::-1]
print(arr_rev)


[1 2 3 4 5]
[5 4 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [ ]:

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# Using flatten()
flattened_array1 = array1.flatten()
print("Flattened using flatten():", flattened_array1)

# Using ravel()
flattened_array2 = array1.ravel()
print("Flattened using ravel():", flattened_array2)

Flattened using flatten(): [1 2 3 2 4 5 1 2 3]
Flattened using ravel(): [1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

# Element-wise comparison
element_wise_comparison = arr1 == arr2
print("Element-wise comparison:\n", element_wise_comparison)

# Array equality
are_equal = np.array_equal(arr1, arr2)
print("\nAre the arrays equal?", are_equal)

Element-wise comparison:
 [[ True  True]
 [ True  True]]

Are the arrays equal? True


(d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
most_frequent_value = np.bincount(x).argmax()
indices = np.where(x == most_frequent_value)[0]

print("Most frequent value in x:", most_frequent_value)
print("Indices of the most frequent value in x:", indices)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
most_freq=np.bincount(y).argmax()
indices_y= np.where(y==most_freq)[0]

print("Most frequent value in y:", most_freq)
print("Indices of the most frequent value in y:", indices_y)


Most frequent value in x: 1
Indices of the most frequent value in x: [0 5 7 8 9]
Most frequent value in y: 1
Indices of the most frequent value in y: [0 1 2]


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg)
sum_all_elements= np.sum(gfg)
print("Sum of all elements:", sum_all_elements)

sum_row_wise= np.sum(gfg, axis=1)
print("Sum of all elements row-wise:", sum_row_wise)

sum_column_wise= np.sum(gfg, axis=0)
print("Sum of all elements column-wise:", sum_column_wise)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

In [ ]:
import numpy as np
n_array=np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print("array:",n_array)

sum_diag=np.diagonal(n_array).sum()
print("Sum of diagonal elements:\n", sum_diag)

eigen_values, eigen_vectors= np.linalg.eig(n_array)
print("Eigen values of matrix:\n", eigen_values)
print("Eigen vectors of matrix:\n", eigen_vectors)

inverse_matrix= np.linalg.inv(n_array)
print("Inverse of matrix:\n", inverse_matrix)

determinant_matrix= np.linalg.det(n_array)
print("Determinant of matrix:", determinant_matrix)


array: [[55 25 15]
 [30 44  2]
 [11 45 77]]
Sum of diagonal elements:
 176
Eigen values of matrix:
 [98.16835147 28.097044   49.73460452]
Eigen vectors of matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]

q = [[4, 5], [6, 7]]

ii. p = [[1, 2], [2, 3], [4, 5]]

q = [[4, 5, 1], [6, 7, 2]]

In [ ]:
p= np.array([[1,2],[2,3]])
q=np.array([[4,5],[6,7]])
answer= np.dot(p,q)

print("The result of multiplying the 2 matrices is:\n", answer)

covariance= np.cov(p,q)
print("The covariance between the 2 matrices is:\n", covariance)

The result of multiplying the 2 matrices is:
 [[16 19]
 [26 31]]
The covariance between the 2 matrices is:
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
p1= np.array([[1,2],[2,3],[4,5]])
q1=np.array([[4,5,1],[6,7,2]])
answer1= np.dot(p1,q1)
print("The result of multiplying the 2 matrices is:\n", answer1)

# Transposing q1 to have the same number of columns as p1
covariance1= np.cov(p1,q1.T)

print("The covariance between the 2 matrices is:\n", covariance1)

The result of multiplying the 2 matrices is:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
The covariance between the 2 matrices is:
 [[0.5 0.5 0.5 1.  1.  0.5]
 [0.5 0.5 0.5 1.  1.  0.5]
 [0.5 0.5 0.5 1.  1.  0.5]
 [1.  1.  1.  2.  2.  1. ]
 [1.  1.  1.  2.  2.  1. ]
 [0.5 0.5 0.5 1.  1.  0.5]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]);
 y = np.array([[1, 5, 0], [5, 10, 3]]),

find inner, outer and cartesian product?

In [2]:
import numpy as np

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner_product= np.inner(x,y)
print("Inner product:\n", inner_product)

outer_product= np.outer(x,y)
print("Outer product:\n", outer_product)

Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


##Q2: Based on NumPy Mathematics and Statistics
(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row



In [6]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
print(array)

# (i) Element-wise absolute value
abs_value= np.abs(array)
print("Element-wise absolute value:\n", abs_value)

#(ii) 25th, 50th, and 75th percentile of flattened array

print("25th percentile of flattened array:", np.percentile(array, 25))
print("50th percentile of flattened array:", np.percentile(array, 50))
print("75th percentile of flattened array:", np.percentile(array, 75))

# For each column
print("\n25th percentile for each column:", np.percentile(array, 25, axis=0))
print("50th percentile for each column:", np.percentile(array, 50, axis=0))
print("75th percentile for each column:", np.percentile(array, 75, axis=0))

# For each row
print("\n25th percentile for each row:", np.percentile(array, 25, axis=1))
print("50th percentile for each row:", np.percentile(array, 50, axis=1))
print("75th percentile for each row:", np.percentile(array, 75, axis=1))

#(iii) Mean, Median and Standard Deviation of flattened array, of each column, and each row
print("\nMean of flattened array:", np.mean(array))
print("Median of flattened array:", np.median(array))
print("Standard Deviation of flattened array:", np.std(array))

[[ 1 -2  3]
 [-4  5 -6]]
Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]
25th percentile of flattened array: -3.5
50th percentile of flattened array: -0.5
75th percentile of flattened array: 2.5

25th percentile for each column: [-2.75 -0.25 -3.75]
50th percentile for each column: [-1.5  1.5 -1.5]
75th percentile for each column: [-0.25  3.25  0.75]

25th percentile for each row: [-0.5 -5. ]
50th percentile for each row: [ 1. -4.]
75th percentile for each row: [2.  0.5]

Mean of flattened array: -0.5
Median of flattened array: -0.5
Standard Deviation of flattened array: 3.8622100754188224


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]).

Find floor, ceiling
and truncated value, rounded values

In [8]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(a)

# floor, ceiling and truncated value, rounded values
print("\nFloor value :", np.floor(a))
print("Ceiling value :", np.ceil(a))
print("Truncated value :", np.trunc(a))
print("Rounded values :", np.round(a))


[-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]

Floor value : [-2. -2. -1.  0.  1.  1.  3.]
Ceiling value : [-1. -1. -0.  1.  2.  2.  3.]
Truncated value : [-1. -1. -0.  0.  1.  1.  3.]
Rounded values : [-2. -2. -0.  0.  2.  2.  3.]


##Q3: Based on Searching and Sorting
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements


In [11]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(array)

# i. Sorted array
sorted_array= np.sort(array)
print("Sorted array:\n", sorted_array)

# ii. Indices of sorted array
indices_sorted_array= np.argsort(array)
print("Indices of sorted array:\n", indices_sorted_array)

# iii. 4 smallest elements
smallest_elements= np.sort(array)[:4]
print("4 smallest elements:\n", smallest_elements)

# iv. 5 largest elements
largest_elements= np.sort(array)[-5:]
print("5 largest elements:\n", largest_elements)

[ 10  52  62  16  16  54 453]
Sorted array:
 [ 10  16  16  52  54  62 453]
Indices of sorted array:
 [0 3 4 1 5 2 6]
4 smallest elements:
 [10 16 16 52]
5 largest elements:
 [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only


In [12]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only
integer_elements= array[array == array.astype(int)]
print("Integer elements only:\n", integer_elements)

# ii. Float elements only
float_elements= array[array != array.astype(int)]
print("Float elements only:\n", float_elements)




Integer elements only:
 [1. 2. 3. 2.]
Float elements only:
 [1.2 2.2]


##Q4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)


In [22]:
import cv2
import numpy as np

def img_to_array(path):

  try:

    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)

    if img is None:
      print(f"Error: Could not read image at {path}")
      return

    # To check if the image is grayscale or RGB
    if len(img.shape) == 2 or img.shape[2] == 1:
      # Grayscale image
      filename = "grayscale_image.txt"
      np.savetxt(filename, img, fmt="%d")
      print(f"Grayscale image saved to {filename}")
    else:
      # RGB image
      filename = "rgb_image.txt"
      # Reshape to 2D array for saving
      reshaped_img = img.reshape(img.shape[0], -1)
      np.savetxt(filename, reshaped_img, fmt="%d")
      print(f"RGB image saved to {filename}")

  except Exception as e:
    print(f"An error occurred: {e}")

dummy_gray = np.zeros((10, 10))
cv2.imwrite("grayscale_image.png", dummy_gray)
dummy_rgb = np.zeros((10, 10, 3))
cv2.imwrite("rgb_image.png", dummy_rgb)

img_to_array("grayscale_image.png")
img_to_array("rgb_image.png")


Grayscale image saved to grayscale_image.txt
RGB image saved to rgb_image.txt


(b) Load the saved file into jupyter notebook?

In [23]:

#(b) Load the saved file into notebook?
# Load the grayscale image
loaded_grayscale_img = np.loadtxt("grayscale_image.txt")
print("Loaded grayscale image:\n", loaded_grayscale_img)

# Load the RGB image
loaded_rgb_img = np.loadtxt("rgb_image.txt")
print("\nLoaded RGB image:\n", loaded_rgb_img)



Loaded grayscale image:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Loaded RGB image:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0